theme: jekyll-theme-minimal
title: Hamidov Siyovush
description: Blockchain Researcher with experience in building CeFi and DeFi systems. Here I share my projects, blog posts, articles and YouTube videos about blockchain security and software development. A place to follow my journey and insights.
